/**
 * Baza de date cu alimente și valori nutriționale per 100g CRUDE (nefierte/nepreprate)
 * Pentru alimentele care se gătesc (carne, cereale, cartofi), valorile sunt CRUDE (raw).
 * Pentru alimentele gata de consum (lactate, conserve, fructe, legume), valorile sunt ca atare.
 * Sursă: USDA FoodData Central + valori standard pentru bucătăria românească
 *
 * maxAmount = cantitate maximă rezonabilă per masă (grame), aplicată la scalare automată
 */
export const FOOD_DB = [
  // ─── CARNE DE PUI (valori CRUDE / raw) ───────────────────────────────────────
  // 1 ou = 60g; carne = gramaj CRUD înainte de gătit
  { name: 'Piept de pui',              aliases: ['piept pui','pui','chicken breast','piept de pui','piept pui crud','piept de pui crud','piept pui fiert','pui fiert','piept pui gratar','pui gratar','piept pui cuptor','pui cuptor','pui la gratar','pui la cuptor','chicken','pui grill'],
                                        per100g: { calories: 120, protein: 22,  carbs: 0,    fat: 2.6 }, maxAmount: 250, category: 'meat' },
  { name: 'Pulpă de pui',              aliases: ['pulpa pui','pulpa de pui','pui pulpa','pulpa pui fara os','pulpa pui copta','chicken thigh'],
                                        per100g: { calories: 172, protein: 17,  carbs: 0,    fat: 11  }, maxAmount: 300, category: 'meat' },

  // ─── CURCAN (valori CRUDE) ────────────────────────────────────────────────────
  { name: 'Piept de curcan',           aliases: ['curcan','piept curcan','curcan crud','curcan fiert','curcan cuptor','curcan la cuptor','turkey breast'],
                                        per100g: { calories: 104, protein: 24,  carbs: 0,    fat: 0.7 }, maxAmount: 250, category: 'meat' },

  // ─── CARNE DE VITĂ (valori CRUDE) ─────────────────────────────────────────────
  { name: 'Carne de vită (slabă)',     aliases: ['vita slaba','vita','carne vita','vita cruda','vita fiarta','vita gratar','steak vita','beef'],
                                        per100g: { calories: 143, protein: 21,  carbs: 0,    fat: 6   }, maxAmount: 250, category: 'meat' },
  { name: 'Carne tocată de vită (10%)',aliases: ['vita tocata','tocatura vita','carne tocata vita','burger vita','vita tocata 10'],
                                        per100g: { calories: 175, protein: 17,  carbs: 0,    fat: 12  }, maxAmount: 200, category: 'meat' },
  { name: 'Carne tocată de vită (20%)',aliases: ['vita tocata grasa','tocatura grasa','vita tocata 20'],
                                        per100g: { calories: 235, protein: 17,  carbs: 0,    fat: 18  }, maxAmount: 200, category: 'meat' },

  // ─── CARNE DE PORC (valori CRUDE) ─────────────────────────────────────────────
  { name: 'Mușchi de porc',            aliases: ['muschi porc','cotlet porc','porc slab','porc gratar','porc la gratar','porc cuptor','porc la cuptor','porc fiert','carne porc'],
                                        per100g: { calories: 143, protein: 21,  carbs: 0,    fat: 6   }, maxAmount: 250, category: 'meat' },

  // ─── PEȘTE (valori CRUDE; conservele rămân ca atare) ─────────────────────────
  { name: 'Somon',                     aliases: ['somon crud','somon cuptor','somon la cuptor','somon gratar','somon la gratar','somon fillet','somon grill','salmon'],
                                        per100g: { calories: 208, protein: 20,  carbs: 0,    fat: 13  }, maxAmount: 200, category: 'fish' },
  { name: 'Ton (conservă în apă)',     aliases: ['ton conserva','ton in apa','ton','tuna'],
                                        per100g: { calories: 116, protein: 26,  carbs: 0,    fat: 1   }, maxAmount: 185, category: 'fish' },
  { name: 'Ton (conservă în ulei)',    aliases: ['ton ulei','ton in ulei','tuna in ulei'],
                                        per100g: { calories: 198, protein: 29,  carbs: 0,    fat: 9   }, maxAmount: 185, category: 'fish' },
  { name: 'Cod',                       aliases: ['cod crud','file cod','cod fiert','cod la cuptor'],
                                        per100g: { calories: 82,  protein: 18,  carbs: 0,    fat: 0.7 }, maxAmount: 200, category: 'fish' },
  { name: 'Tilapia',                   aliases: ['tilapia cruda','tilapia cuptor','tilapia la cuptor'],
                                        per100g: { calories: 96,  protein: 20,  carbs: 0,    fat: 1.7 }, maxAmount: 200, category: 'fish' },
  { name: 'Creveți',                   aliases: ['creveti fierti','creveti cruzi','creveti','shrimp'],
                                        per100g: { calories: 85,  protein: 18,  carbs: 0.9,  fat: 0.5 }, maxAmount: 200, category: 'fish' },
  { name: 'Sardine (conservă)',        aliases: ['sardine conserva','sardine','sardine in apa'],
                                        per100g: { calories: 208, protein: 25,  carbs: 0,    fat: 11  }, maxAmount: 120, category: 'fish' },
  { name: 'Macrou',                    aliases: ['macrou gratar','macrou crud','macrou la gratar'],
                                        per100g: { calories: 205, protein: 19,  carbs: 0,    fat: 14  }, maxAmount: 200, category: 'fish' },
  { name: 'Păstrăv',                  aliases: ['pastrav crud','pastrav cuptor','pastrav la cuptor','pastrav'],
                                        per100g: { calories: 119, protein: 21,  carbs: 0,    fat: 3.5 }, maxAmount: 200, category: 'fish' },
  { name: 'Hering (afumat)',           aliases: ['hering afumat','hering'],
                                        per100g: { calories: 217, protein: 24,  carbs: 0,    fat: 13  }, maxAmount: 150, category: 'fish' },
  { name: 'Crap',                      aliases: ['crap fiert','crap crud','crap la cuptor'],
                                        per100g: { calories: 127, protein: 18,  carbs: 0,    fat: 5.6 }, maxAmount: 250, category: 'fish' },

  // ─── OUĂ (crud; 1 ou întreg = 60g) ──────────────────────────────────────────
  // IMPORTANT: Specificați MEREU în grame (2 ouă = 120g, 3 ouă = 180g — MAX 180g per masă)
  { name: 'Ou întreg',                 aliases: ['ou','oua','ou fiert','oua fierte','ou crud','oua crude','omleta','omleta cu oua','ou omleta','oua omleta','omletă','ou ochi','oua ochi','ochiuri','ou prajit','egg'],
                                        per100g: { calories: 143, protein: 13,  carbs: 0.7,  fat: 9.5 }, maxAmount: 180, gramsPerUnit: 60, category: 'eggs' },
  { name: 'Albuș de ou',               aliases: ['albus fiert','albus','albusuri','albus ou','egg white'],
                                        per100g: { calories: 52,  protein: 11,  carbs: 0.7,  fat: 0.2 }, maxAmount: 240, gramsPerUnit: 30, category: 'eggs' },
  { name: 'Gălbenuș de ou',           aliases: ['galbenus','galbenus ou','egg yolk'],
                                        per100g: { calories: 322, protein: 16,  carbs: 3.6,  fat: 27  }, maxAmount: 90,  gramsPerUnit: 30, category: 'eggs' },

  // ─── LACTATE ─────────────────────────────────────────────────────────────────
  { name: 'Iaurt grecesc (0%)',        aliases: ['iaurt grecesc degresat','iaurt 0%','iaurt grec 0'],
                                        per100g: { calories: 59,  protein: 10,  carbs: 3.6,  fat: 0.4 }, maxAmount: 300, category: 'dairy' },
  { name: 'Iaurt grecesc',             aliases: ['iaurt grecesc','iaurt grec','iaurt 2%','greek yogurt','iaurt grecesc 2%'],
                                        per100g: { calories: 97,  protein: 9,   carbs: 3.6,  fat: 5   }, maxAmount: 300, category: 'dairy' },
  { name: 'Iaurt grecesc (10%)',       aliases: ['iaurt grecesc gras','iaurt 10%','iaurt grec gras'],
                                        per100g: { calories: 133, protein: 8,   carbs: 4,    fat: 9   }, maxAmount: 250, category: 'dairy' },
  { name: 'Iaurt natural',             aliases: ['iaurt natural','iaurt simplu','iaurt','iaurt clasic','iaurt 3.5%'],
                                        per100g: { calories: 61,  protein: 3.5, carbs: 4.7,  fat: 3.3 }, maxAmount: 300, category: 'dairy' },
  { name: 'Lapte (1.5%)',              aliases: ['lapte 1.5','lapte semigresat','lapte semidegresat'],
                                        per100g: { calories: 47,  protein: 3.4, carbs: 4.8,  fat: 1.5 }, maxAmount: 400, category: 'dairy' },
  { name: 'Lapte (3.5%)',              aliases: ['lapte gras','lapte integral','lapte 3.5','lapte'],
                                        per100g: { calories: 61,  protein: 3.2, carbs: 4.8,  fat: 3.3 }, maxAmount: 400, category: 'dairy' },
  { name: 'Lapte (0%)',                aliases: ['lapte degresat','lapte 0%','lapte slab'],
                                        per100g: { calories: 35,  protein: 3.4, carbs: 4.9,  fat: 0.1 }, maxAmount: 400, category: 'dairy' },
  { name: 'Brânză de vaci',           aliases: ['branza vaci','branza proaspata','cottage cheese','branza slaba','branza de vaci slaba','branza de vaci grasa'],
                                        per100g: { calories: 98,  protein: 11,  carbs: 3.4,  fat: 4   }, maxAmount: 200, category: 'dairy' },
  { name: 'Brânză feta',              aliases: ['feta','branza feta','telemea'],
                                        per100g: { calories: 264, protein: 14,  carbs: 4,    fat: 21  }, maxAmount: 60,  category: 'dairy' },
  { name: 'Mozzarella',               aliases: ['branza mozzarella','mozarella','mozzarella'],
                                        per100g: { calories: 280, protein: 28,  carbs: 3,    fat: 17  }, maxAmount: 60,  category: 'dairy' },
  { name: 'Brânză cheddar',           aliases: ['cheddar','branza cheddar'],
                                        per100g: { calories: 402, protein: 25,  carbs: 1.3,  fat: 33  }, maxAmount: 40,  category: 'dairy' },
  { name: 'Brânză ricotta',           aliases: ['ricotta','branza ricotta','branza cottage','cottage'],
                                        per100g: { calories: 174, protein: 11,  carbs: 3,    fat: 13  }, maxAmount: 150, category: 'dairy' },
  { name: 'Parmezan',                 aliases: ['parmezan','parmesan'],
                                        per100g: { calories: 431, protein: 38,  carbs: 4,    fat: 29  }, maxAmount: 30,  category: 'dairy' },
  { name: 'Smântână (15%)',           aliases: ['smantana','smantana 15%','smantana de gatit','sour cream'],
                                        per100g: { calories: 162, protein: 2.7, carbs: 3.4,  fat: 15  }, maxAmount: 60,  category: 'dairy' },
  { name: 'Smântână (30%)',           aliases: ['smantana grasa','smantana 30%','frisca neindulcita'],
                                        per100g: { calories: 285, protein: 2.1, carbs: 3.1,  fat: 30  }, maxAmount: 40,  category: 'dairy' },
  { name: 'Unt',                       aliases: ['unt','butter'],
                                        per100g: { calories: 717, protein: 0.9, carbs: 0.1,  fat: 81  }, maxAmount: 15,  category: 'dairy' },
  { name: 'Chefir',                    aliases: ['chefir','kefir'],
                                        per100g: { calories: 55,  protein: 3.5, carbs: 4,    fat: 2   }, maxAmount: 300, category: 'dairy' },

  // ─── CEREALE CRUDE (cantități înainte de fierbere) ───────────────────────────
  // 80g orez crud → ~200g fiert; 80g paste crude → ~200g fierte
  { name: 'Orez alb (crud)',           aliases: ['orez','orez alb','orez alb crud','orez fiert','orez alb fiert','rice','white rice'],
                                        per100g: { calories: 365, protein: 7,   carbs: 80,   fat: 0.7 }, maxAmount: 120, category: 'grains' },
  { name: 'Orez brun (crud)',          aliases: ['orez brun','orez integral','orez brun crud','orez brun fiert','orez integral fiert','brown rice'],
                                        per100g: { calories: 370, protein: 8,   carbs: 77,   fat: 2.9 }, maxAmount: 120, category: 'grains' },
  { name: 'Orez basmati (crud)',       aliases: ['basmati','orez basmati','orez basmati crud','orez basm fiert'],
                                        per100g: { calories: 360, protein: 8,   carbs: 78,   fat: 0.7 }, maxAmount: 120, category: 'grains' },
  { name: 'Paste (crude)',             aliases: ['paste','paste fierte','spaghete','spaghete fierte','taietei','pasta'],
                                        per100g: { calories: 350, protein: 12,  carbs: 71,   fat: 1.5 }, maxAmount: 100, category: 'grains' },
  { name: 'Paste integrale (crude)',   aliases: ['paste integrale','paste integrale fierte','spaghete integrale'],
                                        per100g: { calories: 350, protein: 14,  carbs: 69,   fat: 2   }, maxAmount: 100, category: 'grains' },
  { name: 'Penne (crude)',             aliases: ['penne','penne fierte'],
                                        per100g: { calories: 350, protein: 12,  carbs: 71,   fat: 1.5 }, maxAmount: 100, category: 'grains' },
  { name: 'Fulgi de ovăz',            aliases: ['ovaz','fulgi ovaz','oats','fulgi de ovaz','oatmeal','terci ovaz','porridge','terci de ovaz','ovaz gatit'],
                                        per100g: { calories: 389, protein: 17,  carbs: 66,   fat: 7   }, maxAmount: 100, category: 'grains' },
  { name: 'Pâine albă',               aliases: ['paine alba','paine','toast alb','toast'],
                                        per100g: { calories: 265, protein: 9,   carbs: 49,   fat: 3.2 }, maxAmount: 80,  category: 'grains' },
  { name: 'Pâine integrală',          aliases: ['paine integrala','paine graham','paine neagra','toast integral'],
                                        per100g: { calories: 247, protein: 9,   carbs: 41,   fat: 3.4 }, maxAmount: 80,  category: 'grains' },
  { name: 'Pâine de secară',          aliases: ['paine secara','paine de secara','paine rye'],
                                        per100g: { calories: 259, protein: 8.5, carbs: 48,   fat: 3.3 }, maxAmount: 80,  category: 'grains' },
  { name: 'Quinoa (crudă)',            aliases: ['quinoa','quinoa cruda','quinoa fiarta','quinoa gatita'],
                                        per100g: { calories: 368, protein: 14,  carbs: 64,   fat: 6   }, maxAmount: 100, category: 'grains' },
  { name: 'Mălai (crud)',              aliases: ['malai','mamaliga','mamaliga gatita','polenta','polenta gatita','malai crud'],
                                        per100g: { calories: 359, protein: 9,   carbs: 74,   fat: 3.5 }, maxAmount: 80,  category: 'grains' },
  { name: 'Hrișcă (crudă)',           aliases: ['hrisca','hrisca cruda','hrisca fiarta','buckwheat'],
                                        per100g: { calories: 343, protein: 13,  carbs: 71,   fat: 3.4 }, maxAmount: 100, category: 'grains' },
  { name: 'Orz (crud)',               aliases: ['orz','orz crud','orz fiert','barley'],
                                        per100g: { calories: 354, protein: 12,  carbs: 73,   fat: 2.3 }, maxAmount: 100, category: 'grains' },
  { name: 'Couscous (crud)',          aliases: ['couscous','couscous crud','couscous fiert','cuscus'],
                                        per100g: { calories: 376, protein: 13,  carbs: 77,   fat: 0.6 }, maxAmount: 100, category: 'grains' },
  { name: 'Bulgur (crud)',            aliases: ['bulgur','bulgur crud','bulgur fiert'],
                                        per100g: { calories: 342, protein: 12,  carbs: 76,   fat: 1.3 }, maxAmount: 100, category: 'grains' },

  // ─── CARTOFI (cruzi) ─────────────────────────────────────────────────────────
  { name: 'Cartofi',                   aliases: ['cartofi','cartofi cruzi','cartofi fierti','cartofi albi','cartofi cuptor','cartofi coapti','cartofi la cuptor','piure cartofi','piure de cartofi','piure','potato'],
                                        per100g: { calories: 77,  protein: 2,   carbs: 17,   fat: 0.1 }, maxAmount: 350, category: 'starch' },
  { name: 'Cartofi dulci',             aliases: ['cartofi dulci','batata','cartofi dulci fierti','cartofi dulci cuptor','batata fiarta','sweet potato'],
                                        per100g: { calories: 86,  protein: 1.6, carbs: 20,   fat: 0.1 }, maxAmount: 300, category: 'starch' },
  { name: 'Cartofi prăjiți',          aliases: ['cartofi prajiti','chips','french fries'],
                                        per100g: { calories: 312, protein: 3.4, carbs: 41,   fat: 15  }, maxAmount: 150, category: 'starch' },

  // ─── LEGUMINOASE (gata fierte / din conservă) ───────────────────────────────
  { name: 'Năut (fiert/conservă)',     aliases: ['naut fiert','naut','chickpeas','naut conserva'],
                                        per100g: { calories: 164, protein: 9,   carbs: 27,   fat: 2.6 }, maxAmount: 200, category: 'legumes' },
  { name: 'Linte roșie (fiartă)',      aliases: ['linte fiarta','linte rosie','linte rosie fiarta','linte'],
                                        per100g: { calories: 116, protein: 9,   carbs: 20,   fat: 0.4 }, maxAmount: 200, category: 'legumes' },
  { name: 'Linte verde (fiartă)',      aliases: ['linte verde fiarta','linte verde'],
                                        per100g: { calories: 116, protein: 9,   carbs: 20,   fat: 0.4 }, maxAmount: 200, category: 'legumes' },
  { name: 'Fasole roșie (fiartă)',     aliases: ['fasole rosie fiarta','fasole rosie','fasole boabe','fasole','fasole alba','fasole alba fiarta'],
                                        per100g: { calories: 127, protein: 8.7, carbs: 23,   fat: 0.5 }, maxAmount: 200, category: 'legumes' },
  { name: 'Fasole verde (fiartă)',     aliases: ['fasole verde fiarta','fasole verde','green beans','pastaie','pastai','fasole pastaie'],
                                        per100g: { calories: 35,  protein: 2,   carbs: 7,    fat: 0.2 }, maxAmount: 300, category: 'legumes' },
  { name: 'Mazăre (fiartă/conservă)', aliases: ['mazare fiarta','mazare verde','mazare verde fiarta','mazare','peas','mazare conserva'],
                                        per100g: { calories: 81,  protein: 5.4, carbs: 14,   fat: 0.4 }, maxAmount: 200, category: 'legumes' },
  { name: 'Edamame',                   aliases: ['edamame','soia fiarta','edamame fierte'],
                                        per100g: { calories: 122, protein: 11,  carbs: 8.9,  fat: 5.2 }, maxAmount: 200, category: 'legumes' },
  { name: 'Tofu',                      aliases: ['tofu','tofu ferm','tofu natural','tofu prajit','tofu extra ferm'],
                                        per100g: { calories: 76,  protein: 8,   carbs: 1.9,  fat: 4.2 }, maxAmount: 200, category: 'legumes' },
  { name: 'Hummus',                    aliases: ['hummus'],
                                        per100g: { calories: 166, protein: 7.9, carbs: 14,   fat: 9.6 }, maxAmount: 100, category: 'legumes' },
  { name: 'Tempeh',                    aliases: ['tempeh'],
                                        per100g: { calories: 193, protein: 19,  carbs: 9.4,  fat: 11  }, maxAmount: 200, category: 'legumes' },

  // ─── LEGUME ──────────────────────────────────────────────────────────────────
  { name: 'Broccoli (fiert)',           aliases: ['broccoli fiert','broccoli','brocoli'],                        per100g: { calories: 35,  protein: 2.4, carbs: 7,    fat: 0.4 }, category: 'vegetables' },
  { name: 'Conopidă (fiartă)',          aliases: ['conopida fiarta','conopida'],                                 per100g: { calories: 31,  protein: 2.5, carbs: 5,    fat: 0.4 }, category: 'vegetables' },
  { name: 'Spanac (fiert)',             aliases: ['spanac fiert','spanac','baby spinach fiert'],                 per100g: { calories: 23,  protein: 2.9, carbs: 3.6,  fat: 0.4 }, category: 'vegetables' },
  { name: 'Spanac (crud)',              aliases: ['spanac crud','spanac proaspat','baby spinach'],               per100g: { calories: 23,  protein: 2.9, carbs: 3.6,  fat: 0.4 }, category: 'vegetables' },
  { name: 'Morcov (crud)',              aliases: ['morcov crud','morcov','morcovi','carrot'],                    per100g: { calories: 41,  protein: 0.9, carbs: 10,   fat: 0.2 }, category: 'vegetables' },
  { name: 'Morcov (fiert)',             aliases: ['morcov fiert','morcovi fierti'],                              per100g: { calories: 35,  protein: 0.8, carbs: 8,    fat: 0.2 }, category: 'vegetables' },
  { name: 'Ardei gras (crud)',          aliases: ['ardei gras','ardei','ardei gras crud','ardei rosu','ardei galben','ardei verde','bell pepper'], per100g: { calories: 31, protein: 1, carbs: 6, fat: 0.3 }, category: 'vegetables' },
  { name: 'Ardei gras (copt)',          aliases: ['ardei copt','ardei gras copt'],                               per100g: { calories: 28,  protein: 1,   carbs: 6,    fat: 0.3 }, category: 'vegetables' },
  { name: 'Roșii (crude)',              aliases: ['rosii','rosie','tomate','tomata','roșii'],                    per100g: { calories: 18,  protein: 0.9, carbs: 3.9,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Roșii cherry',              aliases: ['rosii cherry','cherry tomatoes'],                              per100g: { calories: 18,  protein: 0.9, carbs: 3.9,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Castraveți (cruzi)',         aliases: ['castravete','castraveti','castraveti cruzi','cucumber'],       per100g: { calories: 15,  protein: 0.7, carbs: 3.6,  fat: 0.1 }, category: 'vegetables' },
  { name: 'Salată verde (crudă)',       aliases: ['salata verde','salata','frunze salata','lettuce','rucola'],   per100g: { calories: 15,  protein: 1.4, carbs: 2.9,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Ceapă (crudă)',              aliases: ['ceapa cruda','ceapa','ceapa rosie','ceapa galbena','onion'],  per100g: { calories: 40,  protein: 1.1, carbs: 9,    fat: 0.1 }, category: 'vegetables' },
  { name: 'Ceapă (călită)',             aliases: ['ceapa calita','ceapa sotata','ceapa prajita'],                per100g: { calories: 57,  protein: 0.9, carbs: 13,   fat: 0.2 }, category: 'vegetables' },
  { name: 'Ceapă verde',               aliases: ['ceapa verde','ceapa de primavara','green onion'],             per100g: { calories: 32,  protein: 1.8, carbs: 7.3,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Dovlecel (fiert)',           aliases: ['dovlecel fiert','dovlecel','zucchini','zucchini fiert'],      per100g: { calories: 17,  protein: 1.2, carbs: 3.5,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Dovlecel (la grătar)',       aliases: ['dovlecel gratar','zucchini gratar'],                          per100g: { calories: 20,  protein: 1.3, carbs: 4,    fat: 0.3 }, category: 'vegetables' },
  { name: 'Vinete (la cuptor)',         aliases: ['vinete cuptor','vinete','vinete coapte','eggplant'],          per100g: { calories: 25,  protein: 1,   carbs: 6,    fat: 0.2 }, category: 'vegetables' },
  { name: 'Ciuperci (crude)',           aliases: ['ciuperci crude','ciuperci','champignon','mushrooms'],         per100g: { calories: 22,  protein: 3.1, carbs: 3.3,  fat: 0.3 }, category: 'vegetables' },
  { name: 'Ciuperci (la tigaie)',       aliases: ['ciuperci prajite','ciuperci sotate','ciuperci la tigaie'],    per100g: { calories: 29,  protein: 2.2, carbs: 4.4,  fat: 0.4 }, category: 'vegetables' },
  { name: 'Varză albă (crudă)',         aliases: ['varza cruda','varza','varza alba','cabbage'],                 per100g: { calories: 25,  protein: 1.3, carbs: 5.8,  fat: 0.1 }, category: 'vegetables' },
  { name: 'Varză roșie (crudă)',        aliases: ['varza rosie','varza rosie cruda','red cabbage'],              per100g: { calories: 31,  protein: 1.4, carbs: 7,    fat: 0.2 }, category: 'vegetables' },
  { name: 'Porumb (fiert)',             aliases: ['porumb fiert','porumb','porumb dulce','corn'],                per100g: { calories: 96,  protein: 3.4, carbs: 21,   fat: 1.5 }, category: 'vegetables' },
  { name: 'Țelină (crudă)',             aliases: ['telina cruda','telina','radacina telina','celeriac'],         per100g: { calories: 42,  protein: 1.5, carbs: 9.2,  fat: 0.3 }, category: 'vegetables' },
  { name: 'Sparanghel (fiert)',         aliases: ['sparanghel fiert','sparanghel','asparagus'],                  per100g: { calories: 22,  protein: 2.4, carbs: 4.1,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Praz (fiert)',               aliases: ['praz fiert','praz','leek'],                                  per100g: { calories: 31,  protein: 0.8, carbs: 7.6,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Usturoi (crud)',             aliases: ['usturoi','usturoi crud','garlic'],                            per100g: { calories: 149, protein: 6.4, carbs: 33,   fat: 0.5 }, category: 'vegetables' },
  { name: 'Gulii',                      aliases: ['gulii','gulie','kohlrabi'],                                   per100g: { calories: 27,  protein: 1.7, carbs: 6.2,  fat: 0.1 }, category: 'vegetables' },
  { name: 'Sfeclă roșie (fiartă)',      aliases: ['sfecla rosie','sfecla','beet','sfecla fiarta'],               per100g: { calories: 43,  protein: 1.6, carbs: 9.6,  fat: 0.2 }, category: 'vegetables' },
  { name: 'Ridichi',                    aliases: ['ridichi','radish'],                                           per100g: { calories: 16,  protein: 0.7, carbs: 3.4,  fat: 0.1 }, category: 'vegetables' },
  { name: 'Nap',                        aliases: ['nap','turnip'],                                              per100g: { calories: 28,  protein: 0.9, carbs: 6.4,  fat: 0.1 }, category: 'vegetables' },
  { name: 'Kale (crud)',                aliases: ['kale','kale crud','varza kale'],                              per100g: { calories: 49,  protein: 4.3, carbs: 8.8,  fat: 0.9 }, category: 'vegetables' },

  // ─── FRUCTE ──────────────────────────────────────────────────────────────────
  { name: 'Banană',                     aliases: ['banana','banane','banana medie'],                             per100g: { calories: 89,  protein: 1.1, carbs: 23,   fat: 0.3 }, gramsPerUnit: 120, category: 'fruits' },
  { name: 'Măr',                        aliases: ['mar','mere','apple'],                                        per100g: { calories: 52,  protein: 0.3, carbs: 14,   fat: 0.2 }, gramsPerUnit: 180, category: 'fruits' },
  { name: 'Portocală',                  aliases: ['portocala','portocale','orange'],                             per100g: { calories: 47,  protein: 0.9, carbs: 12,   fat: 0.1 }, gramsPerUnit: 150, category: 'fruits' },
  { name: 'Lămâie',                     aliases: ['lamaie','lamai','zeama lamaie','lemon'],                     per100g: { calories: 29,  protein: 1.1, carbs: 9,    fat: 0.3 }, gramsPerUnit: 100, category: 'fruits' },
  { name: 'Fructe de pădure (mix)',     aliases: ['fructe de padure','berries','mix berries'],                  per100g: { calories: 57,  protein: 0.7, carbs: 14,   fat: 0.3 }, category: 'fruits' },
  { name: 'Afine',                      aliases: ['afine','blueberries'],                                       per100g: { calories: 57,  protein: 0.7, carbs: 14,   fat: 0.3 }, category: 'fruits' },
  { name: 'Căpșuni',                    aliases: ['capsuni','strawberries','capsune'],                          per100g: { calories: 32,  protein: 0.7, carbs: 7.7,  fat: 0.3 }, category: 'fruits' },
  { name: 'Zmeură',                     aliases: ['zmeura','raspberries'],                                      per100g: { calories: 52,  protein: 1.2, carbs: 12,   fat: 0.7 }, category: 'fruits' },
  { name: 'Cireșe / Vișine',           aliases: ['cirese','ciresele','visine','cherry'],                       per100g: { calories: 50,  protein: 1,   carbs: 12,   fat: 0.3 }, gramsPerUnit: 10,  category: 'fruits' },
  { name: 'Kiwi',                       aliases: ['kiwi'],                                                      per100g: { calories: 61,  protein: 1.1, carbs: 15,   fat: 0.5 }, gramsPerUnit: 70,  category: 'fruits' },
  { name: 'Mango',                      aliases: ['mango'],                                                     per100g: { calories: 60,  protein: 0.8, carbs: 15,   fat: 0.4 }, gramsPerUnit: 250, category: 'fruits' },
  { name: 'Ananas',                     aliases: ['ananas','pineapple'],                                        per100g: { calories: 50,  protein: 0.5, carbs: 13,   fat: 0.1 }, gramsPerUnit: 700, category: 'fruits' },
  { name: 'Pepene roșu',               aliases: ['pepene rosu','pepene','watermelon'],                          per100g: { calories: 30,  protein: 0.6, carbs: 7.6,  fat: 0.2 }, category: 'fruits' },
  { name: 'Struguri',                   aliases: ['struguri','grapes'],                                         per100g: { calories: 69,  protein: 0.7, carbs: 18,   fat: 0.2 }, category: 'fruits' },
  { name: 'Pere',                       aliases: ['para','pere','pear'],                                        per100g: { calories: 57,  protein: 0.4, carbs: 15,   fat: 0.1 }, gramsPerUnit: 170, category: 'fruits' },
  { name: 'Piersică',                  aliases: ['piersica','piersici','nectarina','peach'],                    per100g: { calories: 39,  protein: 0.9, carbs: 10,   fat: 0.3 }, gramsPerUnit: 150, category: 'fruits' },
  { name: 'Prune',                      aliases: ['pruna','prune','plum'],                                      per100g: { calories: 46,  protein: 0.7, carbs: 11,   fat: 0.3 }, gramsPerUnit: 50,  category: 'fruits' },
  { name: 'Avocado',                    aliases: ['avocado'],                                                   per100g: { calories: 160, protein: 2,   carbs: 9,    fat: 15  }, gramsPerUnit: 150, category: 'fruits' },
  { name: 'Grepfrut',                  aliases: ['grapefruit','grepfrut'],                                      per100g: { calories: 42,  protein: 0.8, carbs: 11,   fat: 0.1 }, gramsPerUnit: 230, category: 'fruits' },
  { name: 'Mandarine',                  aliases: ['mandarina','mandarine','tangerine'],                         per100g: { calories: 53,  protein: 0.8, carbs: 13,   fat: 0.3 }, gramsPerUnit: 80,  category: 'fruits' },
  { name: 'Smochine',                   aliases: ['smochina','smochine','fig'],                                 per100g: { calories: 74,  protein: 0.8, carbs: 19,   fat: 0.3 }, gramsPerUnit: 40,  category: 'fruits' },
  { name: 'Curmale',                    aliases: ['curmalea','curmale','dates'],                                 per100g: { calories: 282, protein: 2.5, carbs: 75,   fat: 0.4 }, gramsPerUnit: 8,   category: 'fruits' },

  // ─── NUCI & SEMINȚE ──────────────────────────────────────────────────────────
  { name: 'Migdale',                   aliases: ['migdale crude','migdale','almonds'],
                                        per100g: { calories: 579, protein: 21,  carbs: 22,   fat: 50  }, maxAmount: 40, category: 'nuts' },
  { name: 'Nuci',                      aliases: ['nuci crude','nuci','walnuts'],
                                        per100g: { calories: 654, protein: 15,  carbs: 14,   fat: 65  }, maxAmount: 40, category: 'nuts' },
  { name: 'Caju',                      aliases: ['caju crud','caju','cashews'],
                                        per100g: { calories: 553, protein: 18,  carbs: 30,   fat: 44  }, maxAmount: 40, category: 'nuts' },
  { name: 'Alune de pădure',           aliases: ['alune padure','alune','hazelnuts'],
                                        per100g: { calories: 628, protein: 15,  carbs: 17,   fat: 61  }, maxAmount: 40, category: 'nuts' },
  { name: 'Arahide',                   aliases: ['arahide crude','arahide','peanuts','alune americane'],
                                        per100g: { calories: 567, protein: 26,  carbs: 16,   fat: 49  }, maxAmount: 40, category: 'nuts' },
  { name: 'Fistic',                    aliases: ['fistic','pistachios','fistic crud'],
                                        per100g: { calories: 560, protein: 20,  carbs: 28,   fat: 45  }, maxAmount: 40, category: 'nuts' },
  { name: 'Semințe de chia',           aliases: ['seminte chia','chia','chia seeds'],
                                        per100g: { calories: 486, protein: 17,  carbs: 42,   fat: 31  }, maxAmount: 30, category: 'nuts' },
  { name: 'Semințe de in',             aliases: ['seminte in','in','flaxseeds','seminte de in'],
                                        per100g: { calories: 534, protein: 18,  carbs: 29,   fat: 42  }, maxAmount: 30, category: 'nuts' },
  { name: 'Semințe de dovleac',        aliases: ['seminte dovleac','seminte de dovleac','pumpkin seeds'],
                                        per100g: { calories: 559, protein: 30,  carbs: 11,   fat: 49  }, maxAmount: 30, category: 'nuts' },
  { name: 'Semințe de floarea soarelui', aliases: ['seminte floarea soarelui','seminte floarea-soarelui','sunflower seeds'],
                                        per100g: { calories: 584, protein: 21,  carbs: 20,   fat: 51  }, maxAmount: 30, category: 'nuts' },
  { name: 'Semințe de susan',          aliases: ['susan','seminte susan','sesame','susan negru'],
                                        per100g: { calories: 573, protein: 18,  carbs: 23,   fat: 50  }, maxAmount: 20, category: 'nuts' },
  { name: 'Unt de arahide',            aliases: ['unt arahide','unt de arahide','peanut butter'],
                                        per100g: { calories: 588, protein: 25,  carbs: 20,   fat: 50  }, maxAmount: 30, category: 'nuts' },
  { name: 'Tahini',                    aliases: ['tahini','pasta susan'],
                                        per100g: { calories: 595, protein: 17,  carbs: 21,   fat: 54  }, maxAmount: 20, category: 'nuts' },

  // ─── ULEIURI & GRĂSIMI ───────────────────────────────────────────────────────
  { name: 'Ulei de măsline',           aliases: ['ulei masline','ulei de masline','olive oil','ulei'],
                                        per100g: { calories: 884, protein: 0,   carbs: 0,    fat: 100 }, maxAmount: 20, category: 'fats' },
  { name: 'Ulei de cocos',             aliases: ['ulei cocos','ulei de cocos','coconut oil'],
                                        per100g: { calories: 892, protein: 0,   carbs: 0,    fat: 99  }, maxAmount: 15, category: 'fats' },
  { name: 'Ulei de floarea soarelui',  aliases: ['ulei floarea soarelui','ulei vegetal','sunflower oil'],
                                        per100g: { calories: 884, protein: 0,   carbs: 0,    fat: 100 }, maxAmount: 20, category: 'fats' },
  { name: 'Ulei de avocado',           aliases: ['ulei avocado','avocado oil'],
                                        per100g: { calories: 884, protein: 0,   carbs: 0,    fat: 100 }, maxAmount: 20, category: 'fats' },

  // ─── CONDIMENTE & ALTELE ─────────────────────────────────────────────────────
  { name: 'Miere',                     aliases: ['miere de albine','miere','honey'],
                                        per100g: { calories: 304, protein: 0.3, carbs: 82,   fat: 0   }, maxAmount: 20, category: 'other' },
  { name: 'Sirop de arțar',           aliases: ['sirop artar','maple syrup'],
                                        per100g: { calories: 260, protein: 0,   carbs: 67,   fat: 0.1 }, maxAmount: 20, category: 'other' },
  { name: 'Zahăr',                     aliases: ['zahar','zahar alb','sugar'],
                                        per100g: { calories: 387, protein: 0,   carbs: 100,  fat: 0   }, maxAmount: 20, category: 'other' },
  { name: 'Pudră de cacao',            aliases: ['cacao','cacao praf','pudra cacao','cocoa powder'],
                                        per100g: { calories: 228, protein: 19,  carbs: 58,   fat: 14  }, maxAmount: 20, category: 'other' },
  { name: 'Pudră de proteine',         aliases: ['proteina praf','zer proteic','whey protein','protein powder','pudra proteine','shake proteic'],
                                        per100g: { calories: 400, protein: 80,  carbs: 8,    fat: 5   }, maxAmount: 40, category: 'other' },
  { name: 'Mustar',                    aliases: ['mustar','mustard'],
                                        per100g: { calories: 60,  protein: 3.7, carbs: 5.8,  fat: 3.3 }, maxAmount: 20, category: 'other' },
  { name: 'Sos de soia',               aliases: ['sos soia','soy sauce','tamari'],
                                        per100g: { calories: 53,  protein: 8.1, carbs: 4.9,  fat: 0.1 }, maxAmount: 20, category: 'other' },
  { name: 'Oțet balsamic',            aliases: ['otet balsamic','balsamic'],
                                        per100g: { calories: 88,  protein: 0.5, carbs: 17,   fat: 0   }, maxAmount: 20, category: 'other' },
  { name: 'Dressing de iaurt',        aliases: ['dressing iaurt','sos iaurt','iaurt dressing'],
                                        per100g: { calories: 90,  protein: 2,   carbs: 8,    fat: 5   }, maxAmount: 50, category: 'other' },
];

/**
 * Returnează numărul de alimente din baza de date
 */
export function getFoodCount() {
  return FOOD_DB.length;
}
