'use client';

import { useState, useEffect, useRef } from 'react';
import ClientForm from '@/app/components/MealPlanGenerator/ClientForm';
import MealPlan from '@/app/components/MealPlanGenerator/MealPlan';
import styles from '@/app/generator-plan/generator.module.css';

export default function InlinePlanGenerator({ clientId, onBack, onPlanGenerated }) {
  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [queueStatus, setQueueStatus] = useState(null);
  const [error, setError] = useState(null);
  const [clientData, setClientData] = useState(null);
  const [nutritionalNeeds, setNutritionalNeeds] = useState(null);
  const [macroToast, setMacroToast] = useState(null);
  const [toastHiding, setToastHiding] = useState(false);
  const [successMessage, setSuccessMessage] = useState(null);
  const autoGeneratedRef = useRef(false);
  const abortControllerRef = useRef(null);
  const previousNeedsRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    return () => { isMountedRef.current = false; };
  }, []);

  const handleGeneratePlan = async (formData, isRegeneration = false) => {
    abortControllerRef.current?.abort();
    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    if (isRegeneration && nutritionalNeeds) {
      previousNeedsRef.current = { ...nutritionalNeeds };
    }

    setLoading(true);
    setLoadingStep(0);
    setLoadingProgress(0);
    setError(null);
    setClientData(formData);
    let redirecting = false;

    // Salvează în sessionStorage pentru generare în background
    if (formData.clientId) {
      sessionStorage.setItem('generatingPlanClientId', formData.clientId);
      sessionStorage.setItem('generatingPlanStatus', JSON.stringify({
        isGenerating: true,
        currentStep: 0,
        totalSteps: 7,
        startTime: Date.now()
      }));
    }

    try {
      const token = localStorage.getItem('token');
      if (!token) throw new Error('Token de autentificare lipsă. Vă rog reconectați.');

      // Scrie imediat în DB că generarea a început — ÎNAINTE de fetch-ul SSE
      // Astfel, dacă utilizatorul dă back rapid, badge-ul apare instantaneu la polling
      if (formData.clientId) {
        fetch('/api/generation-status', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`,
          },
          body: JSON.stringify({
            clientId: formData.clientId,
            status: 'generating',
            currentStep: 0,
          }),
        }).catch(() => {}); // fire-and-forget, eroarea e necritică
        // Notifică ClientsList să repornească polling-ul imediat
        window.dispatchEvent(new Event('generationStarted'));
      }

      const response = await fetch('/api/generate-meal-plan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
        signal: abortController.signal,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Eroare la generarea planului alimentar');
      }

      const contentType = response.headers.get('Content-Type') || '';
      if (contentType.includes('application/json')) {
        const data = await response.json();
        if (data.type === 'optimal_progress') {
          setSuccessMessage(data.message);
          return;
        }
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';
      let streamDone = false;

      while (true) {
        const { done, value } = await reader.read();
        if (done || streamDone) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.trim()) continue;
          const event = JSON.parse(line);
          if (event.type === 'progress') {
            setLoadingStep(event.day);
            setLoadingProgress(Math.round((event.day / event.total) * 90));
            // Actualizează sessionStorage cu progresul
            if (formData.clientId) {
              sessionStorage.setItem(`generatingPlan_${formData.clientId}`, JSON.stringify({
                isGenerating: true,
                currentStep: event.day,
                totalSteps: event.total,
                startTime: Date.now()
              }));
            }
          } else if (event.type === 'complete') {
            setLoadingProgress(100);
            
            // planId vine ca event.planId (nu event.plan.id)
            const planId = event.planId || event.plan?.id;
            
            // Notifică imediat pentru refresh notificări și badge-uri
            window.dispatchEvent(new Event('generationFinished'));
            
            // Curăță sessionStorage pentru a semnala finalizarea generării
            if (clientId) {
              sessionStorage.removeItem(`generatingPlan_${clientId}`);
              sessionStorage.setItem('generatedPlanResult', JSON.stringify({
                plan: event.plan,
                nutritionalNeeds: event.nutritionalNeeds,
                clientId: clientId,
                timestamp: Date.now()
              }));
            }
            
            // Dacă vine din dashboard (clientId setat), tranziție automată spre vizualizare plan
            if (onPlanGenerated && planId && clientId) {
              redirecting = true;
              streamDone = true;
              setTimeout(() => {
                if (isMountedRef.current) {
                  onPlanGenerated(planId);
                }
              }, 500);
              break;
            }
            
            // Doar dacă NU vine din dashboard, afișăm planul inline
            setMealPlan(event.plan);
            setNutritionalNeeds(event.nutritionalNeeds);

            // NU afișăm macro toast când vine din progres (clientId setat)
            if (isRegeneration && previousNeedsRef.current && !clientId) {
              const newNeeds = event.nutritionalNeeds;
              const oldNeeds = previousNeedsRef.current;
              const adjustments = [];
              const fields = [
                { key: 'calories', name: 'Calorii', unit: 'kcal' },
                { key: 'protein', name: 'Proteine', unit: 'g' },
                { key: 'carbs', name: 'Carbohidrati', unit: 'g' },
                { key: 'fat', name: 'Grasimi', unit: 'g' },
              ];
              for (const f of fields) {
                if (newNeeds[f.key] !== oldNeeds[f.key]) {
                  adjustments.push({ name: f.name, old: oldNeeds[f.key], new: newNeeds[f.key], unit: f.unit, diff: newNeeds[f.key] - oldNeeds[f.key] });
                }
              }
              if (adjustments.length > 0) {
                setMacroToast(adjustments);
                setTimeout(() => {
                  setToastHiding(true);
                  setTimeout(() => { setMacroToast(null); setToastHiding(false); }, 250);
                }, 6000);
              }
              previousNeedsRef.current = null;
            }
          } else if (event.type === 'error') {
            throw new Error(event.message);
          }
        }
      }
    } catch (err) {
      if (err.name === 'AbortError') {
        // La abort, PĂSTREAZĂ starea în sessionStorage - generarea continuă pe server
        return;
      }
      setError(err.message);
      // Șterge la eroare
      if (formData.clientId) {
        sessionStorage.removeItem(`generatingPlan_${formData.clientId}`);
        // Marchează ca eșuat în DB dacă am scris anterior 'generating' din client
        const token = localStorage.getItem('token');
        if (token) {
          fetch('/api/generation-status', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
            body: JSON.stringify({ clientId: formData.clientId, status: 'failed', errorMessage: err.message }),
          }).catch(() => {});
        }
      }
    } finally {
      if (!redirecting) setLoading(false);
    }
  };

  // Auto-generate when clientId is provided
  useEffect(() => {
    if (!clientId) return;
    if (autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;

    const token = localStorage.getItem('token');
    if (!token) return;

    // Verifică dacă există o generare în curs pentru acest client
    const generatingStatus = sessionStorage.getItem(`generatingPlan_${clientId}`);
    
    if (generatingStatus) {
      // Afișează loading-ul cu progresul curent - generarea continuă în background
      try {
        const status = JSON.parse(generatingStatus);
        setLoading(true);
        setLoadingStep(status.currentStep || 0);
        setLoadingProgress(status.currentStep ? Math.round((status.currentStep / 7) * 90) : 0);
        // Nu mai face nimic altceva - polling-ul va detecta când se finalizează
        return;
      } catch (e) {
        console.error('Error parsing generating status:', e);
      }
    }

    // Citește datele de progres stocate din InlineProgressView
    let storedProgress = null;
    let previousNeeds = null;
    let oldWeight = null;
    try {
      storedProgress = JSON.parse(sessionStorage.getItem('clientProgress') || 'null');
      previousNeeds = JSON.parse(sessionStorage.getItem('clientPreviousNeeds') || 'null');
      const storedOldWeight = sessionStorage.getItem('clientOldWeight');
      if (storedOldWeight) {
        oldWeight = storedOldWeight;
      }
    } catch { /* ignoră erori de parse */ }
    sessionStorage.removeItem('clientProgress');
    sessionStorage.removeItem('clientPreviousNeeds');
    sessionStorage.removeItem('clientOldWeight');

    fetch(`/api/clients/${clientId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        if (!data.client) throw new Error(data.error || 'Client negasit');
        const c = data.client;
        
        const formData = {
          clientId,
          name: c.name,
          age: String(c.age),
          weight: oldWeight || String(c.weight), // Folosește greutatea VECHE stocată sau cea din profil
          height: String(c.height),
          gender: c.gender || 'M',
          goal: c.goal || 'maintenance',
          activityLevel: c.activity_level || 'moderate',
          dietType: c.diet_type || 'omnivore',
          allergies: c.allergies || '',
          mealsPerDay: String(c.meals_per_day || '3'),
          foodPreferences: c.food_preferences || '',
        };
        
        if (storedProgress) {
          formData.progress = storedProgress;
        }
        
        // Dacă avem necesarul anterior, adăugăm caloriile actuale pentru ajustare corectă
        if (previousNeeds && previousNeeds.calories) {
          formData.currentPlanCalories = previousNeeds.calories;
        }
        
        
        // Restaurează necesarul anterior pentru toast-ul de diff macro
        if (previousNeeds) {
          previousNeedsRef.current = previousNeeds;
        }
        
        handleGeneratePlan(formData, !!storedProgress);
      })
      .catch(err => setError(err.message));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId]);

  // Polling pentru a verifica progresul generării în background
  useEffect(() => {
    if (!clientId || !loading) return;

    const pollInterval = setInterval(async () => {
      // Verifică statusul coadei
      try {
        const queueRes = await fetch('/api/queue-status');
        if (queueRes.ok) {
          const queueData = await queueRes.json();
          if (queueData.queued > 0 || queueData.processing >= queueData.maxConcurrent) {
            setQueueStatus(queueData);
          } else {
            setQueueStatus(null);
          }
        }
      } catch (e) {
        // Ignore queue status errors
      }

      // Actualizează progresul din sessionStorage
      const generatingStatus = sessionStorage.getItem(`generatingPlan_${clientId}`);
      if (generatingStatus) {
        try {
          const status = JSON.parse(generatingStatus);
          setLoadingStep(status.currentStep || 0);
          setLoadingProgress(status.currentStep ? Math.round((status.currentStep / 7) * 90) : 0);
        } catch (e) {
          console.error('Error parsing status:', e);
        }
      } else {
        // Dacă nu mai există status, înseamnă că s-a finalizat
        // Încearcă să re-fetch planul
        const token = localStorage.getItem('token');
        if (token) {
          fetch(`/api/clients/${clientId}`, {
            headers: { 'Authorization': `Bearer ${token}` },
          })
            .then(res => res.json())
            .then(data => {
              if (data.client && onPlanGenerated) {
                // Verifică dacă clientul are plan
                fetch('/api/meal-plans', {
                  headers: { 'Authorization': `Bearer ${token}` },
                })
                  .then(res => res.json())
                  .then(plansData => {
                    const clientPlan = plansData.plans?.[clientId];
                    if (clientPlan && clientPlan.planId) {
                      setLoading(false);
                      onPlanGenerated(clientPlan.planId);
                    }
                  });
              }
            })
            .catch(console.error);
        }
      }
    }, 500);

    return () => clearInterval(pollInterval);
  }, [clientId, loading, onPlanGenerated]);

  useEffect(() => {
    return () => {
      // NU oprim request-ul dacă există clientId - lăsăm generarea să continue în background
      if (!clientId) {
        abortControllerRef.current?.abort();
      }
    };
  }, [clientId]);

  const handleReset = () => {
    if (clientId) {
      onBack();
    } else {
      setMealPlan(null);
      setClientData(null);
      setNutritionalNeeds(null);
      setError(null);
    }
  };

  const handleRegenerate = (progressData) => {
    const regenerateData = { ...clientData, progress: progressData };
    setMealPlan(null);
    setError(null);
    handleGeneratePlan(regenerateData, true);
  };

  const closeToast = () => {
    setToastHiding(true);
    setTimeout(() => { setMacroToast(null); setToastHiding(false); }, 250);
  };

  return (
    <div className={styles.content}>
      {!clientId && (
        <div style={{ padding: '0 0 20px' }}>
          <button
            onClick={onBack}
            style={{
              display: 'inline-flex', alignItems: 'center', gap: '7px',
              background: 'transparent',
              border: '1px solid #e5e5e5',
            borderRadius: '8px',
            cursor: 'pointer',
            fontSize: '13px', fontWeight: '500', color: '#666',
            padding: '6px 12px 6px 9px',
            transition: 'background 0.14s, border-color 0.14s, color 0.14s',
            fontFamily: 'inherit',
          }}
          onMouseEnter={e => { e.currentTarget.style.background = '#f5f5f5'; e.currentTarget.style.borderColor = '#d4d4d4'; e.currentTarget.style.color = '#111'; }}
          onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#e5e5e5'; e.currentTarget.style.color = '#666'; }}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6"/>
          </svg>
          Înapoi la clienți
        </button>
        </div>
      )}

      {!mealPlan || clientId ? (
        <>
          {loading ? (
            <div className={styles.loadingWrapper}>
              <button 
                style={{
                  position: 'absolute',
                  top: '20px',
                  left: '20px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  width: '40px',
                  height: '40px',
                  background: 'transparent',
                  border: '1px solid #e8e8ed',
                  borderRadius: '8px',
                  color: '#666',
                  cursor: 'pointer',
                  flexShrink: 0,
                  transition: 'background 0.14s, border-color 0.14s, color 0.14s',
                  zIndex: 100,
                  fontFamily: 'inherit',
                }}
                onClick={() => onBack && onBack()}
                onMouseEnter={e => { e.currentTarget.style.background = '#f5f5f7'; e.currentTarget.style.borderColor = '#d4d4d8'; e.currentTarget.style.color = '#111'; }}
                onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#e8e8ed'; e.currentTarget.style.color = '#666'; }}
                aria-label="Înapoi"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="15 18 9 12 15 6" />
                </svg>
              </button>
              <div className={styles.loadingBox}>
                <p className={styles.loadingTitle}>Se generează planul alimentar</p>
                <p className={styles.loadingStep}>
                  {loadingStep > 0 ? `Ziua ${loadingStep} din 7...` : 'Se pregateste...'}
                </p>
                {queueStatus && queueStatus.queued > 0 && (
                  <div className={styles.queueStatus}>
                    <span className={styles.queueIcon}>⏳</span>
                    <span>
                      {queueStatus.queued} {queueStatus.queued === 1 ? 'cerere în așteptare' : 'cereri în așteptare'}
                      {queueStatus.estimatedWaitTime > 0 && ` (~${Math.ceil(queueStatus.estimatedWaitTime / 60)} min)`}
                    </span>
                  </div>
                )}
                <div className={styles.progressTrack}>
                  <div className={styles.progressFill} style={{ width: `${loadingProgress}%` }} />
                </div>
                <div className={styles.progressDots}>
                  {[1, 2, 3, 4, 5, 6, 7].map((d) => (
                    <div
                      key={d}
                      className={`${styles.progressDot} ${
                        d < loadingStep ? styles.progressDotDone :
                        d === loadingStep ? styles.progressDotActive : ''
                      }`}
                    />
                  ))}
                </div>
              </div>
            </div>
          ) : (
            !clientId && <ClientForm onSubmit={handleGeneratePlan} loading={loading} />
          )}
          {successMessage && (
            <div className={styles.success}>
              <span className={styles.successIcon}>✓</span>
              <span>{successMessage}</span>
              <button className={styles.successClose} onClick={() => { setSuccessMessage(null); onBack(); }}>✕</button>
            </div>
          )}
          {error && (
            <div style={{ position: 'relative', paddingTop: '80px', paddingLeft: '20px', paddingRight: '20px', width: '100%' }}>
              <button 
                style={{
                  position: 'absolute',
                  top: '20px',
                  left: '20px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  width: '40px',
                  height: '40px',
                  background: 'transparent',
                  border: '1px solid #e8e8ed',
                  borderRadius: '8px',
                  color: '#666',
                  cursor: 'pointer',
                  flexShrink: 0,
                  transition: 'background 0.14s, border-color 0.14s, color 0.14s',
                  zIndex: 100,
                  fontFamily: 'inherit',
                }}
                onClick={() => onBack && onBack()}
                onMouseEnter={e => { e.currentTarget.style.background = '#f5f5f7'; e.currentTarget.style.borderColor = '#d4d4d8'; e.currentTarget.style.color = '#111'; }}
                onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#e8e8ed'; e.currentTarget.style.color = '#666'; }}
                aria-label="Înapoi"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="15 18 9 12 15 6" />
                </svg>
              </button>
              <div className={styles.error}>
                <span className={styles.errorIcon}>⚠️</span>
                <span>{error}</span>
              </div>
            </div>
          )}
        </>
      ) : !clientId ? (
        <MealPlan
          plan={mealPlan}
          clientData={clientData}
          nutritionalNeeds={nutritionalNeeds}
          onReset={handleReset}
          onRegenerate={handleRegenerate}
        />
      ) : null}

      {macroToast && (
        <div className={`${styles.macroToast} ${toastHiding ? styles.toastHiding : ''}`}>
          <div className={styles.toastHeader}>
            <div className={styles.toastTitle}>
              <span className={styles.toastIcon}>📊</span>
              Macro-uri ajustate
            </div>
            <button className={styles.toastClose} onClick={closeToast}>✕</button>
          </div>
          <div className={styles.toastBody}>
            {macroToast.map((item, idx) => (
              <div key={idx} className={styles.macroRow}>
                <span className={styles.macroName}>{item.name}</span>
                <div className={styles.macroDiff}>
                  <span className={styles.macroOld}>{item.old}{item.unit}</span>
                  <span className={styles.macroArrow}>→</span>
                  <span className={styles.macroNew}>{item.new}{item.unit}</span>
                  <span className={`${styles.macroChange} ${item.diff > 0 ? styles.macroUp : item.diff < 0 ? styles.macroDown : styles.macroSame}`}>
                    {item.diff > 0 ? '+' : ''}{item.diff}{item.unit}
                  </span>
                </div>
              </div>
            ))}
          </div>
          <div className={styles.toastProgress}>
            <div className={styles.toastProgressBar} />
          </div>
        </div>
      )}
    </div>
  );
}
