'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import { useAuth } from '@/app/contexts/AuthContext';
import { ProtectedRoute } from '@/app/components/ProtectedRoute';
import AppHeader from '@/app/components/AppHeader';
import WorkoutPlanForm from '@/app/components/WorkoutPlanGenerator/WorkoutPlanForm';
import styles from './generator.module.css';

const WorkoutPlan = dynamic(() => import('@/app/components/WorkoutPlanGenerator/WorkoutPlan'), {
  ssr: false,
  loading: () => (
    <div className={styles.loadingContainer}>
      <div className={styles.loadingSpinner} />
      <p>Se încarcă planul...</p>
    </div>
  )
});

function GeneratorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const clientId = searchParams.get('clientId');
  const { user } = useAuth();

  const [workoutPlan, setWorkoutPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [error, setError] = useState(null);
  const [clientData, setClientData] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);

  const autoGeneratedRef = useRef(false);
  const abortControllerRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;
    return () => { isMountedRef.current = false; };
  }, []);

  const handleGenerateWorkoutPlan = async (formData) => {
    abortControllerRef.current?.abort();
    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    setLoading(true);
    setLoadingStep(0);
    setLoadingProgress(0);
    setError(null);
    setClientData(formData);

    try {
      const token = localStorage.getItem('token');
      if (!token) throw new Error('Token de autentificare lipsă. Vă rog reconectați.');

      const response = await fetch('/api/generate-workout-plan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
        signal: abortController.signal,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Eroare la generarea planului de antrenament');
      }

      setLoadingStep(1);
      setLoadingProgress(40);

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.trim()) continue;
          const event = JSON.parse(line);
          if (event.type === 'progress') {
            const step = event.step === event.total ? 7 : 1;
            setLoadingStep(step);
            setLoadingProgress(Math.round((step / 7) * 90));
          } else if (event.type === 'complete') {
            setLoadingStep(7);
            setLoadingProgress(100);
            setWorkoutPlan(event.plan);
            const planId = event.planId || event.plan?.id;
            if (planId) {
              setTimeout(() => {
                if (isMountedRef.current) {
                  router.push(`/workout-plan/${planId}`);
                }
              }, 1500);
            }
          } else if (event.type === 'error') {
            throw new Error(event.message);
          }
        }
      }
    } catch (err) {
      if (err.name === 'AbortError') return;
      if (err.message && err.message.includes('limita')) {
        router.push('/upgrade?reason=client_limit');
        return;
      }
      setError(err.message);
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate when clientId is present
  useEffect(() => {
    if (!clientId) return;
    if (autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;

    const token = localStorage.getItem('token');
    if (!token) return;

    fetch(`/api/clients/${clientId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        if (!data.client) throw new Error(data.error || 'Client negăsit');
        const c = data.client;
        const formData = {
          clientId,
          name: c.name,
          age: String(c.age),
          weight: String(c.weight),
          height: String(c.height),
          gender: c.gender || 'M',
          trainingSplit: c.training_split || 'Full Body',
          workoutsPerWeek: String(Math.max(2, Math.min(5, Number(c.workouts_per_week) || 3))),
          fitnessLevel: c.fitness_level || 'beginner',
          availableEquipment: c.available_equipment || 'full gym',
          fitnessGoal: c.fitness_goal || 'muscle gain',
          injuriesLimitations: c.injuries_limitations || '',
          workoutPreferences: c.workout_preferences || '',
        };
        handleGenerateWorkoutPlan(formData);
      })
      .catch(err => setError(err.message));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId]);

  useEffect(() => {
    return () => {
      if (!clientId) abortControllerRef.current?.abort();
    };
  }, [clientId]);

  const handleReset = () => {
    if (clientId) {
      router.push('/clients');
    } else {
      setWorkoutPlan(null);
      setClientData(null);
      setError(null);
    }
  };

  const backTarget = clientId ? '/clients' : '/dashboard';

  return (
    <div className={styles.container}>
      <AppHeader
        title={clientId && clientData ? clientData.name : 'Generator Antrenament'}
        backHref={backTarget}
      />

      <div className={styles.content}>
        {!workoutPlan ? (
          <>
            {loading ? (
              <div className={styles.loadingWrapper}>
                <button
                  style={{
                    position: 'absolute',
                    top: '20px',
                    left: '20px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: '40px',
                    height: '40px',
                    background: 'transparent',
                    border: '1px solid #e8e8ed',
                    borderRadius: '8px',
                    color: '#666',
                    cursor: 'pointer',
                    flexShrink: 0,
                    transition: 'background 0.14s, border-color 0.14s, color 0.14s',
                    zIndex: 100,
                    fontFamily: 'inherit',
                  }}
                  onClick={() => router.push(clientId ? '/clients' : '/dashboard')}
                  onMouseEnter={e => { e.currentTarget.style.background = '#f5f5f7'; e.currentTarget.style.borderColor = '#d4d4d8'; e.currentTarget.style.color = '#111'; }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#e8e8ed'; e.currentTarget.style.color = '#666'; }}
                  aria-label="Înapoi"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="15 18 9 12 15 6" />
                  </svg>
                </button>
                <div className={styles.loadingBox}>
                  <p className={styles.loadingTitle}>Se generează planul de antrenament</p>
                  <p className={styles.loadingStep}>
                    {loadingStep > 0 ? `Ziua ${loadingStep} din 7...` : 'Se pregateste...'}
                  </p>
                  <div className={styles.progressTrack}>
                    <div
                      className={styles.progressFill}
                      style={{ width: `${loadingProgress}%` }}
                    />
                  </div>
                  <div className={styles.progressDots}>
                    {[1, 2, 3, 4, 5, 6, 7].map((d) => (
                      <div
                        key={d}
                        className={`${styles.progressDot} ${
                          d < loadingStep ? styles.progressDotDone :
                          d === loadingStep ? styles.progressDotActive : ''
                        }`}
                      />
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              !clientId && (
                <WorkoutPlanForm onSubmit={handleGenerateWorkoutPlan} loading={loading} />
              )
            )}
            {successMessage && (
              <div className={styles.success}>
                <span className={styles.successIcon}>✓</span>
                <span>{successMessage}</span>
                <button className={styles.successClose} onClick={() => setSuccessMessage(null)}>✕</button>
              </div>
            )}
            {error && (
              <div style={{ position: 'relative', paddingTop: '80px', paddingLeft: '20px', paddingRight: '20px', width: '100%' }}>
                <button
                  style={{
                    position: 'absolute',
                    top: '20px',
                    left: '20px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    width: '40px',
                    height: '40px',
                    background: 'transparent',
                    border: '1px solid #e8e8ed',
                    borderRadius: '8px',
                    color: '#666',
                    cursor: 'pointer',
                    flexShrink: 0,
                    transition: 'background 0.14s, border-color 0.14s, color 0.14s',
                    zIndex: 100,
                    fontFamily: 'inherit',
                  }}
                  onClick={() => router.push(clientId ? '/clients' : '/dashboard')}
                  onMouseEnter={e => { e.currentTarget.style.background = '#f5f5f7'; e.currentTarget.style.borderColor = '#d4d4d8'; e.currentTarget.style.color = '#111'; }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.borderColor = '#e8e8ed'; e.currentTarget.style.color = '#666'; }}
                  aria-label="Înapoi"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="15 18 9 12 15 6" />
                  </svg>
                </button>
                <div className={styles.error}>
                  <span className={styles.errorIcon}>⚠️</span>
                  <span>{error}</span>
                </div>
              </div>
            )}
          </>
        ) : (
          <WorkoutPlan plan={workoutPlan} clientData={clientData} onReset={handleReset} />
        )}
      </div>
    </div>
  );
}

export default function GeneratorAntrenamentPage() {
  return (
    <ProtectedRoute requiredRole="trainer">
      <GeneratorContent />
    </ProtectedRoute>
  );
}
