'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import { useAuth } from '@/app/contexts/AuthContext';
import { FEATURES, getDefaultRedirectURL } from '@/app/config/features';
import { ProtectedRoute } from '@/app/components/ProtectedRoute';
import ClientForm from '@/app/components/MealPlanGenerator/ClientForm';
import AppHeader from '@/app/components/AppHeader';
import styles from './generator.module.css';

// Dynamic import cu ssr: false pentru MealPlan (folosește jsPDF)
const MealPlan = dynamic(() => import('@/app/components/MealPlanGenerator/MealPlan'), {
  ssr: false,
  loading: () => (
    <div className={styles.loadingContainer}>
      <div className={styles.loadingSpinner} />
      <p>Se încarcă planul...</p>
    </div>
  )
});

function GeneratorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const clientId = searchParams.get('clientId');
  const { user } = useAuth();

  // Dacă legacy routes nu sunt permise, redirecționează imediat
  if (!FEATURES.ALLOW_LEGACY_ROUTES) {
    useEffect(() => {
      router.replace(getDefaultRedirectURL());
    }, [router]);
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh' }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: '18px', color: '#666' }}>Redirecționare...</div>
        </div>
      </div>
    );
  }

  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [queueStatus, setQueueStatus] = useState(null);
  const [error, setError] = useState(null);
  const [clientData, setClientData] = useState(null);
  const [nutritionalNeeds, setNutritionalNeeds] = useState(null);
  const [macroToast, setMacroToast] = useState(null);
  const [toastHiding, setToastHiding] = useState(false);
  const [successMessage, setSuccessMessage] = useState(null);
  const autoGeneratedRef = useRef(false);
  const abortControllerRef = useRef(null);
  const previousNeedsRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;
    return () => { isMountedRef.current = false; };
  }, []);

  const handleGeneratePlan = async (formData, isRegeneration = false) => {
    // Anulează orice generare anterioară în curs
    abortControllerRef.current?.abort();
    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    // Salvează valorile anterioare doar pentru regenerare
    if (isRegeneration && nutritionalNeeds) {
      previousNeedsRef.current = { ...nutritionalNeeds };
    }

    setLoading(true);
    setLoadingStep(0);
    setLoadingProgress(0);
    setError(null);
    setClientData(formData);

    // Salvează în sessionStorage pentru generare în background
    if (formData.clientId) {
      sessionStorage.setItem('generatingPlanClientId', formData.clientId);
      sessionStorage.setItem('generatingPlanStatus', JSON.stringify({
        isGenerating: true,
        currentStep: 0,
        totalSteps: 7,
        startTime: Date.now()
      }));
    }

    try {
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('Token de autentificare lipsă. Vă rog reconectați.');
      }

      const response = await fetch('/api/generate-meal-plan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
        signal: abortController.signal,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Eroare la generarea planului alimentar');
      }

      // Verifică dacă răspunsul e JSON simplu (optimal_progress) sau stream
      const contentType = response.headers.get('Content-Type') || '';
      if (contentType.includes('application/json')) {
        // Răspuns JSON simplu (de ex. optimal_progress)
        const data = await response.json();
        if (data.type === 'optimal_progress') {
          // Progres optim - afișăm mesajul verde de succes
          setSuccessMessage(data.message);
          // Curăță sessionStorage
          if (formData.clientId) {
            sessionStorage.removeItem('generatingPlanClientId');
            sessionStorage.removeItem('generatingPlanStatus');
          }
          return;
        }
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.trim()) continue;
          const event = JSON.parse(line);
          if (event.type === 'progress') {
            setLoadingStep(event.day);
            setLoadingProgress(Math.round((event.day / event.total) * 90));
            // Actualizează sessionStorage cu progresul
            if (formData.clientId) {
              sessionStorage.setItem(`generatingPlan_${formData.clientId}`, JSON.stringify({
                isGenerating: true,
                currentStep: event.day,
                totalSteps: event.total,
                startTime: Date.now()
              }));
            }
          } else if (event.type === 'complete') {
            setLoadingProgress(100);
            setMealPlan(event.plan);
            setNutritionalNeeds(event.nutritionalNeeds);
            // Salvează rezultatul în sessionStorage și curăță status
            if (formData.clientId) {
              sessionStorage.setItem('generatedPlanResult', JSON.stringify({
                plan: event.plan,
                nutritionalNeeds: event.nutritionalNeeds,
                clientId: formData.clientId,
                timestamp: Date.now()
              }));
              sessionStorage.removeItem(`generatingPlan_${formData.clientId}`);
            }
            
            // Redirect automat la planul generat după 1.5s
            const planId = event.planId || event.plan?.id;
            if (planId) {
              setTimeout(() => {
                if (isMountedRef.current) {
                  router.push(`/meal-plan/${planId}`);
                }
              }, 1500);
            }
            if (isRegeneration && previousNeedsRef.current) {
              const newNeeds = event.nutritionalNeeds;
              const oldNeeds = previousNeedsRef.current;
              const adjustments = [];
              
              if (newNeeds.calories !== oldNeeds.calories) {
                adjustments.push({
                  name: 'Calorii',
                  old: oldNeeds.calories,
                  new: newNeeds.calories,
                  unit: 'kcal',
                  diff: newNeeds.calories - oldNeeds.calories
                });
              }
              if (newNeeds.protein !== oldNeeds.protein) {
                adjustments.push({
                  name: 'Proteine',
                  old: oldNeeds.protein,
                  new: newNeeds.protein,
                  unit: 'g',
                  diff: newNeeds.protein - oldNeeds.protein
                });
              }
              if (newNeeds.carbs !== oldNeeds.carbs) {
                adjustments.push({
                  name: 'Carbohidrați',
                  old: oldNeeds.carbs,
                  new: newNeeds.carbs,
                  unit: 'g',
                  diff: newNeeds.carbs - oldNeeds.carbs
                });
              }
              if (newNeeds.fat !== oldNeeds.fat) {
                adjustments.push({
                  name: 'Grăsimi',
                  old: oldNeeds.fat,
                  new: newNeeds.fat,
                  unit: 'g',
                  diff: newNeeds.fat - oldNeeds.fat
                });
              }
              
              if (adjustments.length > 0) {
                setMacroToast(adjustments);
                // Auto-close după 6 secunde
                setTimeout(() => {
                  setToastHiding(true);
                  setTimeout(() => {
                    setMacroToast(null);
                    setToastHiding(false);
                  }, 250);
                }, 6000);
              }
              previousNeedsRef.current = null;
            }
          } else if (event.type === 'error') {
            throw new Error(event.message);
          }
        }
      }
    } catch (err) {
      if (err.name === 'AbortError') {
        // La abort, PĂSTREAZĂ starea în sessionStorage - generarea continuă
        return;
      }
      setError(err.message);
      console.error('Error:', err);
      // Șterge la eroare
      if (formData.clientId) {
        sessionStorage.removeItem(`generatingPlan_${formData.clientId}`);
      }
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate when clientId is present in URL
  useEffect(() => {
    if (!clientId) return;
    if (autoGeneratedRef.current) return; // previne dubla execuție din React Strict Mode
    autoGeneratedRef.current = true;

    const token = localStorage.getItem('token');
    if (!token) return;

    // Verifică dacă există un rezultat generat deja
    const generatedResult = sessionStorage.getItem('generatedPlanResult');
    if (generatedResult) {
      try {
        const result = JSON.parse(generatedResult);
        if (result.clientId === clientId) {
          // Afișează rezultatul
          setMealPlan(result.plan);
          setNutritionalNeeds(result.nutritionalNeeds);
          setLoading(false);
          sessionStorage.removeItem('generatedPlanResult');
          return;
        }
      } catch (e) {
        console.error('Error parsing generated result:', e);
      }
    }

    // Verifică dacă există o generare în curs pentru acest client
    const generatingClientId = sessionStorage.getItem('generatingPlanClientId');
    const generatingStatus = sessionStorage.getItem('generatingPlanStatus');
    
    if (generatingClientId === clientId && generatingStatus) {
      // Afișează loading-ul cu progresul curent
      try {
        const status = JSON.parse(generatingStatus);
        setLoading(true);
        setLoadingStep(status.currentStep || 0);
        setLoadingProgress(status.currentStep ? Math.round((status.currentStep / 7) * 90) : 0);
        // Nu relansa generarea - doar afișează progresul
        return;
      } catch (e) {
        console.error('Error parsing generating status:', e);
      }
    }

    // Citește datele de progres stocate de antrenor din panoul de clienți
    const fromProgress = searchParams.get('fromProgress') === 'true';
    let storedProgress = null;
    let previousNeeds = null;
    if (fromProgress) {
      try {
        storedProgress = JSON.parse(sessionStorage.getItem('clientProgress') || 'null');
        previousNeeds  = JSON.parse(sessionStorage.getItem('clientPreviousNeeds') || 'null');
      } catch { /* ignoră erori de parse */ }
      sessionStorage.removeItem('clientProgress');
      sessionStorage.removeItem('clientPreviousNeeds');
    }

    fetch(`/api/clients/${clientId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        if (!data.client) throw new Error(data.error || 'Client negăsit');
        const c = data.client;
        const formData = {
          clientId: clientId,
          name: c.name,
          age: String(c.age),
          weight: storedProgress?.currentWeight ? String(storedProgress.currentWeight) : String(c.weight),
          height: String(c.height),
          gender: c.gender || 'M',
          goal: c.goal || 'maintenance',
          activityLevel: c.activity_level || 'moderate',
          dietType: c.diet_type || 'omnivore',
          allergies: c.allergies || '',
          mealsPerDay: String(c.meals_per_day || '5'),
          foodPreferences: c.food_preferences || '',
        };
        if (storedProgress) {
          formData.progress = storedProgress;
        }
        // Restaurează necesarul anterior pentru toast-ul de diff macro
        if (previousNeeds) {
          previousNeedsRef.current = previousNeeds;
        }
        handleGeneratePlan(formData, !!storedProgress);
      })
      .catch(err => setError(err.message));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId]);

  // Oprește generarea dacă utilizatorul navighează înainte de finalizare
  useEffect(() => {
    return () => {
      // NU oprim request-ul dacă există clientId - lăsăm generarea să continue în background
      if (!clientId) {
        abortControllerRef.current?.abort();
      }
    };
  }, [clientId]);

  // Polling pentru a verifica progresul generării în background
  useEffect(() => {
    if (!clientId || !loading) return;

    const pollInterval = setInterval(async () => {
      // Verifică statusul coadei
      try {
        const queueRes = await fetch('/api/queue-status');
        if (queueRes.ok) {
          const queueData = await queueRes.json();
          if (queueData.queued > 0 || queueData.processing >= queueData.maxConcurrent) {
            setQueueStatus(queueData);
          } else {
            setQueueStatus(null);
          }
        }
      } catch (e) {
        // Ignore queue status errors
      }

      // Verifică dacă s-a finalizat generarea
      const generatedResult = sessionStorage.getItem('generatedPlanResult');
      if (generatedResult) {
        try {
          const result = JSON.parse(generatedResult);
          if (result.clientId === clientId) {
            setMealPlan(result.plan);
            setNutritionalNeeds(result.nutritionalNeeds);
            setLoading(false);
            sessionStorage.removeItem('generatedPlanResult');
            clearInterval(pollInterval);
            return;
          }
        } catch (e) {
          console.error('Error parsing result:', e);
        }
      }

      // Actualizează progresul din sessionStorage
      const generatingStatus = sessionStorage.getItem(`generatingPlan_${clientId}`);
      if (generatingStatus) {
        try {
          const status = JSON.parse(generatingStatus);
          setLoadingStep(status.currentStep || 0);
          setLoadingProgress(status.currentStep ? Math.round((status.currentStep / 7) * 90) : 0);
        } catch (e) {
          console.error('Error parsing status:', e);
        }
      }
    }, 500); // Verifică la fiecare 500ms

    return () => clearInterval(pollInterval);
  }, [clientId, loading]);

  const handleReset = () => {
    if (clientId) {
      router.push('/dashboard');
    } else {
      setMealPlan(null);
      setClientData(null);
      setNutritionalNeeds(null);
      setError(null);
    }
  };

  const handleRegenerate = (progressData) => {
    // Regenerate with progress data included
    const regenerateData = {
      ...clientData,
      progress: progressData,
    };
    setMealPlan(null);
    setError(null);
    handleGeneratePlan(regenerateData, true); // true = isRegeneration
  };

  const closeToast = () => {
    setToastHiding(true);
    setTimeout(() => {
      setMacroToast(null);
      setToastHiding(false);
    }, 250);
  };

  const backTarget = clientId ? '/clients' : '/dashboard';

  return (
    <div className={styles.container}>
      <AppHeader
        title={clientId && clientData ? clientData.name : 'Generator Plan'}
        backHref={backTarget}
      />

      <div className={styles.content}>
        {!mealPlan ? (
          <>
            {loading ? (
              <div className={styles.loadingWrapper}>
                <button 
                  className={styles.loadingBackBtn} 
                  onClick={() => {
                    if (clientId) {
                      router.push('/clients');
                    } else {
                      router.push('/dashboard');
                    }
                  }}
                  aria-label="Înapoi"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="15 18 9 12 15 6" />
                  </svg>
                  Înapoi
                </button>
                <div className={styles.loadingBox}>
                  <p className={styles.loadingTitle}>Se generează planul alimentar</p>
                  <p className={styles.loadingStep}>
                    {loadingStep > 0 ? `Ziua ${loadingStep} din 7...` : 'Se pregătește...'}
                  </p>
                  {queueStatus && queueStatus.queued > 0 && (
                    <div className={styles.queueStatus}>
                      <span className={styles.queueIcon}>⏳</span>
                      <span>
                        {queueStatus.queued} {queueStatus.queued === 1 ? 'cerere în așteptare' : 'cereri în așteptare'}
                        {queueStatus.estimatedWaitTime > 0 && ` (~${Math.ceil(queueStatus.estimatedWaitTime / 60)} min)`}
                      </span>
                    </div>
                  )}
                  <div className={styles.progressTrack}>
                    <div
                      className={styles.progressFill}
                      style={{ width: `${loadingProgress}%` }}
                    />
                  </div>
                  <div className={styles.progressDots}>
                    {[1, 2, 3, 4, 5, 6, 7].map((d) => (
                      <div
                        key={d}
                        className={`${styles.progressDot} ${
                          d < loadingStep ? styles.progressDotDone :
                          d === loadingStep ? styles.progressDotActive : ''
                        }`}
                      />
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              !clientId && <ClientForm onSubmit={handleGeneratePlan} loading={loading} />
            )}
            {successMessage && (
              <div className={styles.success}>
                <span className={styles.successIcon}>✓</span>
                <span>{successMessage}</span>
                <button className={styles.successClose} onClick={() => {
                  setSuccessMessage(null);
                  if (clientId) router.push('/dashboard');
                }}>✕</button>
              </div>
            )}
            {error && (
              <div style={{ position: 'relative', paddingTop: '80px', paddingLeft: '20px', paddingRight: '20px', width: '100%' }}>
                <button 
                  className={styles.loadingBackBtn}
                  style={{ position: 'absolute', top: '20px', left: '20px', zIndex: 100 }}
                  onClick={() => {
                    if (clientId) {
                      router.push('/clients');
                    } else {
                      router.push('/dashboard');
                    }
                  }}
                  aria-label="Înapoi"
                >
                  <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="15 18 9 12 15 6" />
                  </svg>
                  Înapoi
                </button>
                <div className={styles.error}>
                  <span className={styles.errorIcon}>⚠️</span>
                  <span>{error}</span>
                </div>
              </div>
            )}
          </>
        ) : (
          <MealPlan plan={mealPlan} clientData={clientData} nutritionalNeeds={nutritionalNeeds} onReset={handleReset} onRegenerate={handleRegenerate} />
        )}
      </div>

      {/* Toast pentru ajustările macro */}
      {macroToast && (
        <div className={`${styles.macroToast} ${toastHiding ? styles.toastHiding : ''}`}>
          <div className={styles.toastHeader}>
            <div className={styles.toastTitle}>
              <span className={styles.toastIcon}>📊</span>
              Macro-uri ajustate
            </div>
            <button className={styles.toastClose} onClick={closeToast}>✕</button>
          </div>
          <div className={styles.toastBody}>
            {macroToast.map((item, idx) => (
              <div key={idx} className={styles.macroRow}>
                <span className={styles.macroName}>{item.name}</span>
                <div className={styles.macroDiff}>
                  <span className={styles.macroOld}>{item.old}{item.unit}</span>
                  <span className={styles.macroArrow}>→</span>
                  <span className={styles.macroNew}>{item.new}{item.unit}</span>
                  <span className={`${styles.macroChange} ${item.diff > 0 ? styles.macroUp : item.diff < 0 ? styles.macroDown : styles.macroSame}`}>
                    {item.diff > 0 ? '+' : ''}{item.diff}{item.unit}
                  </span>
                </div>
              </div>
            ))}
          </div>
          <div className={styles.toastProgress}>
            <div className={styles.toastProgressBar} />
          </div>
        </div>
      )}
    </div>
  );
}

export default function GeneratorPage() {
  return (
    <ProtectedRoute requiredRole="trainer">
      <GeneratorContent />
    </ProtectedRoute>
  );
}
