'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/app/contexts/AuthContext';
import { ProtectedRoute } from '@/app/components/ProtectedRoute';
import ClientForm from '@/app/components/MealPlanGenerator/ClientForm';
import MealPlan from '@/app/components/MealPlanGenerator/MealPlan';
import AppHeader from '@/app/components/AppHeader';
import styles from './generator.module.css';

function GeneratorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const clientId = searchParams.get('clientId');
  const { user } = useAuth();
  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [error, setError] = useState(null);
  const [clientData, setClientData] = useState(null);
  const [nutritionalNeeds, setNutritionalNeeds] = useState(null);
  const autoGeneratedRef = useRef(false);

  const handleGeneratePlan = async (formData) => {
    setLoading(true);
    setLoadingStep(0);
    setLoadingProgress(0);
    setError(null);
    setClientData(formData);

    try {
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('Token de autentificare lipsă. Vă rog reconectați.');
      }

      const response = await fetch('/api/generate-meal-plan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Eroare la generarea planului alimentar');
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.trim()) continue;
          const event = JSON.parse(line);
          if (event.type === 'progress') {
            setLoadingStep(event.day);
            setLoadingProgress(Math.round((event.day / event.total) * 90));
          } else if (event.type === 'complete') {
            setLoadingProgress(100);
            setMealPlan(event.plan);
            setNutritionalNeeds(event.nutritionalNeeds);
          } else if (event.type === 'error') {
            throw new Error(event.message);
          }
        }
      }
    } catch (err) {
      setError(err.message);
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate when clientId is present in URL
  useEffect(() => {
    if (!clientId) return;
    if (autoGeneratedRef.current) return; // previne dubla execuție din React Strict Mode
    autoGeneratedRef.current = true;

    const token = localStorage.getItem('token');
    if (!token) return;

    fetch(`/api/clients/${clientId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        if (!data.client) throw new Error(data.error || 'Client negăsit');
        const c = data.client;
        handleGeneratePlan({
          clientId: clientId,
          name: c.name,
          age: String(c.age),
          weight: String(c.weight),
          height: String(c.height),
          gender: c.gender || 'M',
          goal: c.goal || 'maintenance',
          activityLevel: c.activity_level || 'moderate',
          dietType: c.diet_type || 'omnivore',
          allergies: c.allergies || '',
          mealsPerDay: String(c.meals_per_day || '3'),
        });
      })
      .catch(err => setError(err.message));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId]);

  const handleReset = () => {
    if (clientId) {
      router.push('/clients');
    } else {
      setMealPlan(null);
      setClientData(null);
      setNutritionalNeeds(null);
      setError(null);
    }
  };

  const backTarget = clientId ? '/clients' : '/dashboard';

  return (
    <div className={styles.container}>
      <AppHeader
        title={clientId && clientData ? clientData.name : 'Generator Plan'}
        backHref={backTarget}
      />

      <div className={styles.content}>
        {!mealPlan ? (
          <>
            {loading ? (
              <div className={styles.loadingWrapper}>
                <div className={styles.loadingBox}>
                  <p className={styles.loadingTitle}>Se generează planul alimentar</p>
                  <p className={styles.loadingStep}>
                    {loadingStep > 0 ? `Ziua ${loadingStep} din 7...` : 'Se pregătește...'}
                  </p>
                  <div className={styles.progressTrack}>
                    <div
                      className={styles.progressFill}
                      style={{ width: `${loadingProgress}%` }}
                    />
                  </div>
                  <div className={styles.progressDots}>
                    {[1, 2, 3, 4, 5, 6, 7].map((d) => (
                      <div
                        key={d}
                        className={`${styles.progressDot} ${
                          d < loadingStep ? styles.progressDotDone :
                          d === loadingStep ? styles.progressDotActive : ''
                        }`}
                      />
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              !clientId && <ClientForm onSubmit={handleGeneratePlan} loading={loading} />
            )}
            {error && (
              <div className={styles.error}>
                <span className={styles.errorIcon}>⚠️</span>
                <span>{error}</span>
              </div>
            )}
          </>
        ) : (
          <>
            <MealPlan plan={mealPlan} clientData={clientData} nutritionalNeeds={nutritionalNeeds} onReset={handleReset} />
          </>
        )}
      </div>
    </div>
  );
}

export default function GeneratorPage() {
  return (
    <ProtectedRoute>
      <GeneratorContent />
    </ProtectedRoute>
  );
}
