'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '@/app/contexts/AuthContext';
import { ProtectedRoute } from '@/app/components/ProtectedRoute';
import ClientForm from '@/app/components/MealPlanGenerator/ClientForm';
import MealPlan from '@/app/components/MealPlanGenerator/MealPlan';
import AppHeader from '@/app/components/AppHeader';
import styles from './generator.module.css';

function GeneratorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const clientId = searchParams.get('clientId');
  const { user } = useAuth();
  const [mealPlan, setMealPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [error, setError] = useState(null);
  const [clientData, setClientData] = useState(null);
  const [nutritionalNeeds, setNutritionalNeeds] = useState(null);
  const [macroToast, setMacroToast] = useState(null);
  const [toastHiding, setToastHiding] = useState(false);
  const [successMessage, setSuccessMessage] = useState(null);
  const autoGeneratedRef = useRef(false);
  const abortControllerRef = useRef(null);
  const previousNeedsRef = useRef(null);

  const handleGeneratePlan = async (formData, isRegeneration = false) => {
    // Anulează orice generare anterioară în curs
    abortControllerRef.current?.abort();
    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    // Salvează valorile anterioare doar pentru regenerare
    if (isRegeneration && nutritionalNeeds) {
      previousNeedsRef.current = { ...nutritionalNeeds };
    }

    setLoading(true);
    setLoadingStep(0);
    setLoadingProgress(0);
    setError(null);
    setClientData(formData);

    try {
      const token = localStorage.getItem('token');
      if (!token) {
        throw new Error('Token de autentificare lipsă. Vă rog reconectați.');
      }

      const response = await fetch('/api/generate-meal-plan', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
        signal: abortController.signal,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Eroare la generarea planului alimentar');
      }

      // Verifică dacă răspunsul e JSON simplu (optimal_progress) sau stream
      const contentType = response.headers.get('Content-Type') || '';
      if (contentType.includes('application/json')) {
        // Răspuns JSON simplu (de ex. optimal_progress)
        const data = await response.json();
        if (data.type === 'optimal_progress') {
          // Progres optim - afișăm mesajul verde de succes
          setSuccessMessage(data.message);
          return;
        }
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop();
        for (const line of lines) {
          if (!line.trim()) continue;
          const event = JSON.parse(line);
          if (event.type === 'progress') {
            setLoadingStep(event.day);
            setLoadingProgress(Math.round((event.day / event.total) * 90));
          } else if (event.type === 'complete') {
            setLoadingProgress(100);
            setMealPlan(event.plan);
            setNutritionalNeeds(event.nutritionalNeeds);
            
            // Afișează toast-ul cu ajustările macro doar la regenerare
            if (isRegeneration && previousNeedsRef.current) {
              const newNeeds = event.nutritionalNeeds;
              const oldNeeds = previousNeedsRef.current;
              const adjustments = [];
              
              if (newNeeds.calories !== oldNeeds.calories) {
                adjustments.push({
                  name: 'Calorii',
                  old: oldNeeds.calories,
                  new: newNeeds.calories,
                  unit: 'kcal',
                  diff: newNeeds.calories - oldNeeds.calories
                });
              }
              if (newNeeds.protein !== oldNeeds.protein) {
                adjustments.push({
                  name: 'Proteine',
                  old: oldNeeds.protein,
                  new: newNeeds.protein,
                  unit: 'g',
                  diff: newNeeds.protein - oldNeeds.protein
                });
              }
              if (newNeeds.carbs !== oldNeeds.carbs) {
                adjustments.push({
                  name: 'Carbohidrați',
                  old: oldNeeds.carbs,
                  new: newNeeds.carbs,
                  unit: 'g',
                  diff: newNeeds.carbs - oldNeeds.carbs
                });
              }
              if (newNeeds.fat !== oldNeeds.fat) {
                adjustments.push({
                  name: 'Grăsimi',
                  old: oldNeeds.fat,
                  new: newNeeds.fat,
                  unit: 'g',
                  diff: newNeeds.fat - oldNeeds.fat
                });
              }
              
              if (adjustments.length > 0) {
                setMacroToast(adjustments);
                // Auto-close după 6 secunde
                setTimeout(() => {
                  setToastHiding(true);
                  setTimeout(() => {
                    setMacroToast(null);
                    setToastHiding(false);
                  }, 250);
                }, 6000);
              }
              previousNeedsRef.current = null;
            }
          } else if (event.type === 'error') {
            throw new Error(event.message);
          }
        }
      }
    } catch (err) {
      if (err.name === 'AbortError') return; // utilizatorul a întrerupt — ieșire silențioasă
      setError(err.message);
      console.error('Error:', err);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate when clientId is present in URL
  useEffect(() => {
    if (!clientId) return;
    if (autoGeneratedRef.current) return; // previne dubla execuție din React Strict Mode
    autoGeneratedRef.current = true;

    const token = localStorage.getItem('token');
    if (!token) return;

    // Citește datele de progres stocate de antrenor din panoul de clienți
    const fromProgress = searchParams.get('fromProgress') === 'true';
    let storedProgress = null;
    let previousNeeds = null;
    if (fromProgress) {
      try {
        storedProgress = JSON.parse(sessionStorage.getItem('clientProgress') || 'null');
        previousNeeds  = JSON.parse(sessionStorage.getItem('clientPreviousNeeds') || 'null');
      } catch { /* ignoră erori de parse */ }
      sessionStorage.removeItem('clientProgress');
      sessionStorage.removeItem('clientPreviousNeeds');
    }

    fetch(`/api/clients/${clientId}`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
      .then(res => res.json())
      .then(data => {
        if (!data.client) throw new Error(data.error || 'Client negăsit');
        const c = data.client;
        const formData = {
          clientId: clientId,
          name: c.name,
          age: String(c.age),
          weight: storedProgress?.currentWeight ? String(storedProgress.currentWeight) : String(c.weight),
          height: String(c.height),
          gender: c.gender || 'M',
          goal: c.goal || 'maintenance',
          activityLevel: c.activity_level || 'moderate',
          dietType: c.diet_type || 'omnivore',
          allergies: c.allergies || '',
          mealsPerDay: String(c.meals_per_day || '3'),
          foodPreferences: c.food_preferences || '',
        };
        if (storedProgress) {
          formData.progress = storedProgress;
        }
        // Restaurează necesarul anterior pentru toast-ul de diff macro
        if (previousNeeds) {
          previousNeedsRef.current = previousNeeds;
        }
        handleGeneratePlan(formData, !!storedProgress);
      })
      .catch(err => setError(err.message));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId]);

  // Oprește generarea dacă utilizatorul navighează înainte de finalizare
  useEffect(() => {
    return () => {
      abortControllerRef.current?.abort();
    };
  }, []);

  const handleReset = () => {
    if (clientId) {
      router.push('/clients');
    } else {
      setMealPlan(null);
      setClientData(null);
      setNutritionalNeeds(null);
      setError(null);
    }
  };

  const handleRegenerate = (progressData) => {
    // Regenerate with progress data included
    const regenerateData = {
      ...clientData,
      progress: progressData,
    };
    setMealPlan(null);
    setError(null);
    handleGeneratePlan(regenerateData, true); // true = isRegeneration
  };

  const closeToast = () => {
    setToastHiding(true);
    setTimeout(() => {
      setMacroToast(null);
      setToastHiding(false);
    }, 250);
  };

  const backTarget = clientId ? '/clients' : '/dashboard';

  return (
    <div className={styles.container}>
      <AppHeader
        title={clientId && clientData ? clientData.name : 'Generator Plan'}
        backHref={backTarget}
      />

      <div className={styles.content}>
        {!mealPlan ? (
          <>
            {loading ? (
              <div className={styles.loadingWrapper}>
                <div className={styles.loadingBox}>
                  <p className={styles.loadingTitle}>Se generează planul alimentar</p>
                  <p className={styles.loadingStep}>
                    {loadingStep > 0 ? `Ziua ${loadingStep} din 7...` : 'Se pregătește...'}
                  </p>
                  <div className={styles.progressTrack}>
                    <div
                      className={styles.progressFill}
                      style={{ width: `${loadingProgress}%` }}
                    />
                  </div>
                  <div className={styles.progressDots}>
                    {[1, 2, 3, 4, 5, 6, 7].map((d) => (
                      <div
                        key={d}
                        className={`${styles.progressDot} ${
                          d < loadingStep ? styles.progressDotDone :
                          d === loadingStep ? styles.progressDotActive : ''
                        }`}
                      />
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              !clientId && <ClientForm onSubmit={handleGeneratePlan} loading={loading} />
            )}
            {successMessage && (
              <div className={styles.success}>
                <span className={styles.successIcon}>✓</span>
                <span>{successMessage}</span>
                <button className={styles.successClose} onClick={() => {
                  setSuccessMessage(null);
                  if (clientId) router.push('/clients');
                }}>✕</button>
              </div>
            )}
            {error && (
              <div className={styles.error}>
                <span className={styles.errorIcon}>⚠️</span>
                <span>{error}</span>
              </div>
            )}
          </>
        ) : (
          <>
            <MealPlan plan={mealPlan} clientData={clientData} nutritionalNeeds={nutritionalNeeds} onReset={handleReset} onRegenerate={handleRegenerate} />
          </>
        )}
      </div>

      {/* Toast pentru ajustările macro */}
      {macroToast && (
        <div className={`${styles.macroToast} ${toastHiding ? styles.toastHiding : ''}`}>
          <div className={styles.toastHeader}>
            <div className={styles.toastTitle}>
              <span className={styles.toastIcon}>📊</span>
              Macro-uri ajustate
            </div>
            <button className={styles.toastClose} onClick={closeToast}>✕</button>
          </div>
          <div className={styles.toastBody}>
            {macroToast.map((item, idx) => (
              <div key={idx} className={styles.macroRow}>
                <span className={styles.macroName}>{item.name}</span>
                <div className={styles.macroDiff}>
                  <span className={styles.macroOld}>{item.old}{item.unit}</span>
                  <span className={styles.macroArrow}>→</span>
                  <span className={styles.macroNew}>{item.new}{item.unit}</span>
                  <span className={`${styles.macroChange} ${item.diff > 0 ? styles.macroUp : item.diff < 0 ? styles.macroDown : styles.macroSame}`}>
                    {item.diff > 0 ? '+' : ''}{item.diff}{item.unit}
                  </span>
                </div>
              </div>
            ))}
          </div>
          <div className={styles.toastProgress}>
            <div className={styles.toastProgressBar} />
          </div>
        </div>
      )}
    </div>
  );
}

export default function GeneratorPage() {
  return (
    <ProtectedRoute requiredRole="trainer">
      <GeneratorContent />
    </ProtectedRoute>
  );
}
